Add Obstacles
ouchiminh/gaei2 pull request #4
Opened 2020-05-02 08:42 UTC by sp-mixer

ドローンに当たり判定を追加しました。
また、適当な障害物を3つ設置しました。当たり判定も追加されています。

2020-05-02 11:09 UTC, ouchiminh commented
障害物が障害物だとコンパイル時に認識できるように適当なクラスを追加することはできますか。
そのクラスでのちのち移動障害物も制御できるようになってほしいです。(静止障害物は移動量0の移動障害物として表現したい)

2020-05-02 13:14 UTC, sp-mixer commented
> 障害物が障害物だとコンパイル時に認識できるように適当なクラスを追加することはできますか。
> そのクラスでのちのち移動障害物も制御できるようになってほしいです。(静止障害物は移動量0の移動障害物として表現したい)

ゲーム的に言えば「敵」のような認識で大丈夫ですか？

2020-05-02 13:24 UTC, ouchiminh commented
そのほうが理解しやすいならそういう認識で大丈夫です。

2020-05-03 15:14 UTC, kongou923 submitted a review, later dismissed

2020-05-04 13:24 UTC, ouchiminh requested changes

2020-05-04 13:24 UTC, ouchiminh commented on 2d/Assets/Scripts/drone_ctrl.cs
> +public class drone_ctrl : MonoBehaviour
```suggestion
public class DroneCtrl : MonoBehaviour
```

2020-05-04 13:24 UTC, ouchiminh commented on 2d/Assets/obstacle_cntr.cs
> +public class obstacle_cntr : MonoBehaviour
controlは普通ctrlと略します。
これを修正するついでに、キャメルケースで書いてみませんか？C#はキャメルケースで書いた方が標準と統一感があって好ましく感じませんか？
```suggestion
public class ObstacleCtrl : MonoBehaviour
```

2020-05-05 07:58 UTC, ouchiminh approved these changes

2020-05-07 01:50 UTC, kongou923 approved these changes

2020-05-08 08:36 UTC, merged